version: "3.8"

services:
  honey-and-thyme:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: honey-and-thyme-web
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
