name: honey_and_thyme
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  file_picker: ^8.0.0+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  http_parser: ^4.0.2
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  web: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/IMFellEnglishSC-Regular.ttf
    - assets/fonts/IMFellEnglish-Regular.ttf
  fonts:
    - family: MarchRough
      fonts:
        - asset: assets/fonts/March-Rough.ttf
