name: honey_and_thyme
description: "Gallery for Honey and Thyme"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  file_picker: ^8.0.0+1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  google_sign_in_web: ^1.0.0
  google_sign_in: ^7.0.0
  http: ^1.2.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  signalr_core: ^1.1.2
  transparent_image: ^2.0.1
  uuid: ^4.5.1
  web: ^0.5.1

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/IMFellEnglishSC-Regular.ttf
    - assets/fonts/IMFellEnglish-Regular.ttf
  fonts:
    - family: MarchRough
      fonts:
        - asset: assets/fonts/March-Rough.ttf
