// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYX7RhBqUUmVtzjYL2zRPPXuRBH6f2Juo',
    appId: '1:332065640580:web:4d425333b2308f9f85b2d1',
    messagingSenderId: '332065640580',
    projectId: 'honey-and-thyme',
    authDomain: 'honey-and-thyme.firebaseapp.com',
    storageBucket: 'honey-and-thyme.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuhyQiebFMF2E6JyXrXTHuWUOsvb8E6us',
    appId: '1:332065640580:android:1ec2fe05854380ac85b2d1',
    messagingSenderId: '332065640580',
    projectId: 'honey-and-thyme',
    storageBucket: 'honey-and-thyme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_v6x6F_i2NATqC3hJz65oymF5aAGxWNs',
    appId: '1:332065640580:ios:64f3e94271b5cbbc85b2d1',
    messagingSenderId: '332065640580',
    projectId: 'honey-and-thyme',
    storageBucket: 'honey-and-thyme.appspot.com',
    iosClientId: '332065640580-rle6qt5sl2enlpjuae6agj8kleqd8juc.apps.googleusercontent.com',
    iosBundleId: 'com.example.honeyAndThyme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_v6x6F_i2NATqC3hJz65oymF5aAGxWNs',
    appId: '1:332065640580:ios:64f3e94271b5cbbc85b2d1',
    messagingSenderId: '332065640580',
    projectId: 'honey-and-thyme',
    storageBucket: 'honey-and-thyme.appspot.com',
    iosClientId: '332065640580-rle6qt5sl2enlpjuae6agj8kleqd8juc.apps.googleusercontent.com',
    iosBundleId: 'com.example.honeyAndThyme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYX7RhBqUUmVtzjYL2zRPPXuRBH6f2Juo',
    appId: '1:332065640580:web:f27c2cbbe389e25685b2d1',
    messagingSenderId: '332065640580',
    projectId: 'honey-and-thyme',
    authDomain: 'honey-and-thyme.firebaseapp.com',
    storageBucket: 'honey-and-thyme.appspot.com',
  );
}
